### ISSUE TITLE
LM4558B or TL072?

### ISSUE THREAD

**Issue by KeLaiFu** [gerb-ster/SCM-140-ADSR#1]
The BOM states LM4558B opamps, but the layout would indicate that standard TL072 should be used, unless I am misunderstanding something?

**Comment by gerb-ster** [comment]
I didn't have a LM4558 opamp in my EagleCad library and since it has the same footprint as a TL072 I've used that one. The original design uses LM4558's, however they are interchangeable, should you not be able to find them.
